AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Gemfile'

Rails:
  Enabled: true

# Bundler/OrderedGems:
#   Enabled: false
#
# Metrics/LineLength:
#   Enabled: false
#
# Style/Documentation:
#   Enabled: false
#
# Style/StringLiterals:
#   Enabled: false
#
# Style/NumericLiterals:
#   Enabled: false
#
# Style/EmptyLinesAroundAccessModifier:
#   Enabled: false
#
# Style/IndentationConsistency:
#   Enabled: false
#
# Style/AndOr:
#   Enabled: false
#
# Style/SpaceInsideBrackets:
#   Enabled: false
#
# Style/EmptyLinesAroundBlockBody:
#   Enabled: false
#
# Style/ClassAndModuleChildren:
#   Enabled: false
